// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgBXeKsdEK7E2e18wf4lhiB4tq6eC8vhQ',
    appId: '1:505394609338:web:b6682433e851636b7b9683',
    messagingSenderId: '505394609338',
    projectId: 'movilproyect-b6bc7',
    authDomain: 'movilproyect-b6bc7.firebaseapp.com',
    storageBucket: 'movilproyect-b6bc7.firebasestorage.app',
    measurementId: 'G-4NVMLE91XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV2Emi1_GxQnM0GyMeKZQMr20b5WUaliw',
    appId: '1:505394609338:android:a64819307735fa1a7b9683',
    messagingSenderId: '505394609338',
    projectId: 'movilproyect-b6bc7',
    storageBucket: 'movilproyect-b6bc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9jrNDywSIbjOjoQuugXc41KK4WgE6JwA',
    appId: '1:505394609338:ios:df2d06650ee222487b9683',
    messagingSenderId: '505394609338',
    projectId: 'movilproyect-b6bc7',
    storageBucket: 'movilproyect-b6bc7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9jrNDywSIbjOjoQuugXc41KK4WgE6JwA',
    appId: '1:505394609338:ios:df2d06650ee222487b9683',
    messagingSenderId: '505394609338',
    projectId: 'movilproyect-b6bc7',
    storageBucket: 'movilproyect-b6bc7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgBXeKsdEK7E2e18wf4lhiB4tq6eC8vhQ',
    appId: '1:505394609338:web:b27ab3edcdd242277b9683',
    messagingSenderId: '505394609338',
    projectId: 'movilproyect-b6bc7',
    authDomain: 'movilproyect-b6bc7.firebaseapp.com',
    storageBucket: 'movilproyect-b6bc7.firebasestorage.app',
    measurementId: 'G-RFVVSNQ9TC',
  );
}
